### ISSUE TITLE
LocalWebCache.js:34

### ISSUE THREAD

**Issue by ideaDevCode** [leifermendez/api-whatsapp-ts#11]
Estoy teniendo un error al intentar levantar el servicio el cual es el siguiente
`C:\Users\vboxuser\Documents\whatsapp-api\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^
TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (C:\Users\vboxuser\Documents\whatsapp-api\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\Users\vboxuser\Documents\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:744:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`
Creí que era algun error de alguna dependecia asi que lo descargue nuevamente, sin embargo sigue sin funcionar, alguien tiene el mismo problema o lo ha solucionado?

**Comment by espinozaguillermo** [comment]
@ideaDevCode me sucede lo mismo, pudiste solucionarlo ? gracias

**Comment by RNatsuki** [comment]
Mismo problema

**Comment by RNatsuki** [comment]
@espinozaguillermo  Parece ser un error de whatsapp-web.js

**Comment by RNatsuki** [comment]
@ideaDevCode He logrado solucioarlo integrando venom en lugar de whatsapp-web.js

**Comment by poolsergio123** [comment]
@RNatsuki como lo hiciste?

**Comment by RNatsuki** [comment]
@poolsergio123  hice un fork puedes intentar proba: https://github.com/RNatsuki/api-whatsapp

**Comment by espinozaguillermo** [comment]
@RNatsuki hice un fork de https://github.com/RNatsuki/api-whatsapp pero al levantar con npm run dev no logra iniciar sesión y queda en loop ![image](https://github.com/leifermendez/api-whatsapp-ts/assets/6461966/624c53d1-9f82-4108-836d-905f45a7a4b1)

**Comment by RNatsuki** [comment]
@espinozaguillermo 
Intenta con el repositorio original de Leifer.

**Comment by eduardocarlostoledo** [comment]
> Estoy teniendo un error al intentar levantar el servicio el cual es el siguiente `C:\Users\vboxuser\Documents\whatsapp-api\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34 const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1]; ^ TypeError: Cannot read properties of null (reading '1') at LocalWebCache.persist (C:\Users\vboxuser\Documents\whatsapp-api\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69) at C:\Users\vboxuser\Documents\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:744:36 at processTicksAndRejections (node:internal/process/task_queues:95:5)` Creí que era algun error de alguna dependecia asi que lo descargue nuevamente, sin embargo sigue sin funcionar, alguien tiene el mismo problema o lo ha solucionado?

Creo que es incompatibilidad entre la version de node que estas usando y la version de ww, yo puse una version anterior y corre, pero no funciona el bot.
