### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Junkboy1** [leifermendez/api-whatsapp-ts#5]
Hola, estoy tratando de implementar el API en Google Compute Engine VM, todo iba bien hasta la parte de npm run dev, estoy obteniendo un error despues del "cargando lead" y al parecer tiene que ver con puppeteer.

Alguna idea de como resolverlo?

npm run dev

> whatsapp-api-yt@1.0.0 dev
> nodemon ./src/app.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node ./src/app.ts`
Ready...3001
Iniciando....
cargado lead
Error: Failed to launch the browser process!
/home/rsa-key-20230222/whatsappapi/api-whatsapp-ts/node_modules/whatsapp-web.js/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/rsa-key-20230222/whatsappapi/api-whatsapp-ts/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/home/rsa-key-20230222/whatsappapi/api-whatsapp-ts/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[nodemon] app crashed - waiting for file changes before starting...

![image](https://user-images.githubusercontent.com/125615430/220768011-68c29cf5-6199-401f-9c15-92f854053474.png)

**Comment by jhernancanom** [comment]
Me too.
El error que recibo es que no puede iniciar el explorador, y que sólo se reconoce la revisión r982053 (adjunto imagen).

¿Cómo hago para saber cuál es la revisión del Chrome que tengo? (adjunto imagen donde muestro la ayuda de Chrome donde veo la versión, pero no está la revisión).

![image](https://user-images.githubusercontent.com/5818845/224519372-52ff6ef6-e20a-43ab-8f7a-a57863687437.png)

![image](https://user-images.githubusercontent.com/5818845/224519378-f18eee42-7e8c-429c-a6ae-c998d1d36fcd.png)

**Comment by sentadoensilla** [comment]
Hola muchachos, a mi me paso lo mismo en un Linux CentOS y cada que instalaba una dependencia me pedia otra, fue frustrante pero se solicono instalando chromium enves de chrome, en el caso de CentOS es sudo yum install chromium, para los debian deben usar apt o apt-get en lugar de yum

**Comment by jhernancanom** [comment]
Buen día, colega.
Si gustas, compartamos conocimiento y juntos echemos a andar esta utilidad.

**Comment by leog1992** [comment]
despues de llorar por tres dias y tres noches, pude instalarlo en un vps. 
instalar nginx
instalar node, npm, n y actualizar a ultima version 

tambien instalar chromium y sus librerias 
apt-get install chromium-browser
sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

instalar tambien sudo apt-get install -y libgbm-dev

crear un usuario y otorgarle permisos: 
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-sudo-enabled-user-on-ubuntu-18-04-quickstart-es

crear carpeta en servidor ngnix darle todos los permisos para poder acceder desde otro usuario
te logueas con el otro usuario y hacer un clone con git en la carepta del servidor
haces los pasos del readme todo con el usuario que no es root
y al dar run dev no te saldra error. 

![image](https://github.com/leifermendez/api-whatsapp-ts/assets/8444234/ec678c56-950a-4b88-afb2-bfff2ce89216)

**Comment by leog1992** [comment]
funcionando
